### ISSUE TITLE
CHARMM: Handle patches

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#22]
Since the CHARMM forcefield only specified patch/residue compatibility with (barely) human-readable comments (see https://github.com/choderalab/openmm-forcefields/pull/1#issuecomment-283505234), we plan to create a YAML file to direct which [ffxml compatibility tags](https://github.com/peastman/openmm/blob/238a10688d85c78ea67dc459ea7f5c458b175673/docs-source/usersguide/application.rst#patches) are to be inserted.

The initial version will cover
* Common N- and C-terminal patches (`NTER`, `CTER`, ACE/NME)
* Disulfides
* Common modifications for kinases (phosphoserine, tyrosine, threonine in different protonation states)

The syntax will look something like
```YAML
charmm-patches.yaml:
---
residues:
   ALA:
      - NTER
      - CTER

patches:
   DISU:
      - 1:CYS
      - 2:CYS
```
In future iterations, we will expand this compatibility list.
