### ISSUE TITLE
OpenMM ffxml water model templates cannot have H-H bonds

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmm-forcefields#56]
We will need to regenerate the CHARMM water models to ensure they do not contain H-H bonds.

cc: https://github.com/pandegroup/openmm/issues/1939#issuecomment-359130400
cc: https://github.com/ParmEd/ParmEd/issues/941

**Comment by jchodera** [comment]
@peastman : I was trying to figure out how this issue slipped through since we actually *test* assigning parameters to a PDB file containing waters in [this test](https://github.com/ParmEd/ParmEd/blob/master/test/test_parmed_openmm.py#L612-L633), and I realized that this test must be passing because the default CHARMM [water parameter file](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/toppar_water_ions.str) actually contains both [TIP3P](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/toppar_water_ions.str#L65-L75) (which contained the artificial H-H bond) and [the MMFF water model](https://github.com/choderalab/openmm-forcefields/blob/master/charmm/toppar/toppar_water_ions.str#L77-L87) (which does not have an H-H bond).

Once we remove the H-H bond from TIP3P, the problem will be that this file will now contain two identical templates. That means we will need some degree of manual processing, which I'd prefer to program via the YAML file. 

What should we do here? My thought is to specify when certain residues are to be excluded from reading, so we can program this to produce two separate files (`waters_ions_default.xml` and `waters_ions_mmff.xml`):

```yaml
- sourcePackage: charmm36
  sourcePackageVersion: toppar_c36_aug15.tgz
- Destination: waters_ions_default.xml
  Source:
    stream:
     - toppar/toppar_water_ions.str
    exclude_residues:
     - TP3M
  References:
   tip3p:
     - >-
       W.L. Jorgensen; J.Chandrasekhar; J.D. Madura; R.W. Impey; M.L. Klein; "Comparison of simple potential functions for
       simulating liquid water", J. Chem. Phys. 79 926-935 (1983).
   ions:
     - >-
       Beglov, D. and Roux, B., Finite Representation of an Infinite Bulk System: Solvent Boundary Potential for
       Computer Simulations, Journal of Chemical Physics, 1994, 100: 9050-9063
     - zinc:
       - >-
         Stote, R.H. and Karplus, M. Zinc Binding in Proteins and Solution: A Simple but Accurate Nonbonded
         Representation, PROTEINS: Structure, Function, and Genetics 23:12-31 (1995)
     - cations:
       - >-
         Won, Y., "Force Field for Monovalent, Divalent, and Trivalent Cations Developed under the Solvent Boundary
         Potential," Journal of Physical Chemistry A., 116: 11763-11767, 2012.
- Destination: waters_ions_mmff.xml
  Source:
    stream:
     - toppar/toppar_water_ions.str
    exclude_residues:
     - TIP3
  References:
   MMFF:
     - >-
       [ref goes here]
   ions:
     - >-
       Beglov, D. and Roux, B., Finite Representation of an Infinite Bulk System: Solvent Boundary Potential for
       Computer Simulations, Journal of Chemical Physics, 1994, 100: 9050-9063
     - zinc:
       - >-
         Stote, R.H. and Karplus, M. Zinc Binding in Proteins and Solution: A Simple but Accurate Nonbonded
         Representation, PROTEINS: Structure, Function, and Genetics 23:12-31 (1995)
     - cations:
       - >-
         Won, Y., "Force Field for Monovalent, Divalent, and Trivalent Cations Developed under the Solvent Boundary
         Potential," Journal of Physical Chemistry A., 116: 11763-11767, 2012.
```
